stages: 
  - 'build'
  - 'deploy'


build project:
  stage: build
  image: node:14
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - build/

netlify:
  stage: deploy
  image: node:14
  script:
    - yarn add global netlify-cli,
    - netlify deploy --dir=build --prod
