stages:
  - "build"
  - "deploy"

build project:
  stage: build
  image: node:14
  script:
    - yarn
    - CI=false yarn build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  image: node:14
  only:
    - main
  script:
    - npm install -g --unsafe-perm=true netlify-cli
    - netlify deploy --dir=build --prod

draft deploy:
  stage: deploy
  image: node:14
  except:
    - main
  script:
    - npm install -g --unsafe-perm=true netlify-cli
    - netlify deploy --dir=build
