stages: 
  - 'build'
  - 'deploy'


build project:
  stage: build
  image: node:14
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - build/

netlify:
  stage: deploy
  image: node:14
  script:
    - npm install -g --unsafe-perm=true netlify-cli
    - netlify deploy --dir=build --prod
